services:
  client:
    image: anyconnect-client:latest
    ports:
      - 5900:5900
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      default:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.tcp_timestamps=0
